# Generated by Django 6.0.4 on 2026-07-17 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('defaulted', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('dcc_flagged', models.BooleanField(default=False)),
                ('cdb_flagged', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LUID', models.CharField(max_length=55)),
                ('endpoint', models.CharField(default='www.loanmasta.com', max_length=255)),
                ('category', models.CharField(blank=True, choices=[('SOLE TRADER', 'SOLE TRADER'), ('SME', 'SME'), ('COMPANY', 'COMPANY')], default='nonmember', max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Miss', 'Miss')], default='', max_length=6, null=True)),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('last_name', models.CharField(blank=True, max_length=55, null=True)),
                ('role', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile1', models.IntegerField(blank=True, null=True)),
                ('mobile2', models.IntegerField(blank=True, null=True)),
                ('ipa', models.FileField(blank=True, null=True, upload_to='ids/', verbose_name='IPA CERTIFICATE:')),
                ('ipa_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ipa_url', models.CharField(blank=True, max_length=555, null=True)),
                ('tin', models.FileField(blank=True, null=True, upload_to='ids/', verbose_name='TIN CERTIFICATE:')),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tin_url', models.CharField(blank=True, max_length=555, null=True)),
                ('sector', models.CharField(blank=True, choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], max_length=10, null=True)),
                ('organisation', models.CharField(blank=True, max_length=110, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('work_phone', models.IntegerField(blank=True, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=55, null=True, unique=True, verbose_name='work email address')),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('use_loanmasta', models.BooleanField(default=False)),
                ('record_count', models.IntegerField(default=0)),
                ('api_key', models.CharField(blank=True, help_text="Shared secret for this tenant's API access (both directions).", max_length=128, null=True)),
                ('feed_enabled', models.BooleanField(default=False, help_text='When on, the automated sync pulls this tenant LMS feed on schedule.')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(choices=[('BASIC', 'BASIC'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], default='BASIC', help_text='Subscription plan; governs default API visibility.', max_length=20)),
                ('can_view_loans', models.BooleanField(default=True, help_text='Tenant may view other-lender loan records in credit checks.')),
                ('can_view_transactions', models.BooleanField(default=False, help_text='Tenant may view repayment transaction history in credit checks.')),
                ('can_view_uploads', models.BooleanField(default=False, help_text='Tenant may view client documents held by DCC.')),
                ('credit_check_enabled', models.BooleanField(default=True, help_text='Master switch for this tenant to run credit checks at all.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
