# Generated by Django 6.0.4 on 2026-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_check_window_hours',
            field=models.PositiveIntegerField(default=12, help_text='Hours a paid credit-check view remains accessible before requiring a new payment.'),
        ),
    ]
