# Generated by Django 6.0.4 on 2026-07-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free Plan'), ('SME', 'SME Plan'), ('BUSINESS', 'Business Plan')], default='FREE', help_text='Subscription plan — matches website pricing tiers.', max_length=20),
        ),
    ]
