# Generated by Django 6.0.4 on 2026-07-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_plan_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrower_onboarding_enabled',
            field=models.BooleanField(default=False, help_text='When enabled and the platform borrower portal is active, new client records created by this tenant automatically receive a PIN email so they can log in to the borrower self-service portal.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watch_digest_mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate (one email per change)'), ('WEEKLY', 'Weekly Digest (every Monday)')], default='IMMEDIATE', help_text='How Watch List alerts are delivered to this tenant.', max_length=10),
        ),
    ]
