# Generated by Django 6.0.4 on 2026-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_owner', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='clientemployer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_employer', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientbankaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bankaccount', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientprofilehistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientupload',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_uploads', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payslip', to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_payslip', to='client.clientemployer'),
        ),
        migrations.AddField(
            model_name='userprofileupload',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_uploads', to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='clientprofile',
            unique_together={('LUID', 'CUID')},
        ),
        migrations.AddIndex(
            model_name='clientprofilehistory',
            index=models.Index(fields=['client', '-changed_at'], name='client_clie_client__8475c6_idx'),
        ),
    ]
