# Generated by Django 6.0.4 on 2026-07-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=500, help_text='0–1000 composite credit score.')),
                ('grade', models.CharField(choices=[('AAA', 'AAA – Exceptional'), ('AA', 'AA – Excellent'), ('A', 'A – Very Good'), ('BBB', 'BBB – Good'), ('BB', 'BB – Fair'), ('B', 'B – Below Average'), ('CCC', 'CCC – Poor'), ('CC', 'CC – Bad'), ('C', 'C – Very Bad')], default='BBB', max_length=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('total_loans', models.IntegerField(default=0)),
                ('completed_loans', models.IntegerField(default=0)),
                ('active_loans', models.IntegerField(default=0)),
                ('defaulted_loans', models.IntegerField(default=0)),
                ('arrears_loans', models.IntegerField(default=0)),
                ('recovery_loans', models.IntegerField(default=0)),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to='client.clientprofile')),
            ],
        ),
    ]
