# Generated by Django 6.0.4 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_identity_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbankaccount',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
