# Generated by Django 6.0.4 on 2026-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_branch_name_max_length'),
        ('users', '0003_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='dcc_status',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('SETTLED', 'SETTLED DEFAULT'), ('RECOVERY', 'RECOVERY'), ('BAD', 'BAD'), ('BACKLIST', 'BLACKLIST')], default='CLEAR', max_length=20, null=True, verbose_name='DCC Status'),
        ),
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('CREDIT_CHECK', 'Credit Check Authorization'), ('DATA_SHARE', 'Data Sharing to DCC'), ('THIRD_PARTY', 'Third-Party Access'), ('MARKETING', 'Marketing')], max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('PAPER', 'Paper Form'), ('DIGITAL', 'Digital Signature'), ('VERBAL', 'Verbal (Recorded)'), ('APP', 'Mobile App')], default='PAPER', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='consents/')),
                ('is_active', models.BooleanField(default=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='client.clientprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_obtained', to='users.userprofile')),
            ],
            options={
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='DefaultNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ref', models.CharField(blank=True, help_text='Loan reference (optional)', max_length=100)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to DCC'), ('NOTIFIED', 'Borrower Notified'), ('LISTED', 'Default Listed'), ('SETTLED', 'Settled — Default Removed'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn by Lender')], default='DRAFT', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notification_method', models.CharField(blank=True, max_length=20)),
                ('grace_days', models.PositiveIntegerField(default=14)),
                ('grace_expires_at', models.DateTimeField(blank=True, null=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('listed_by', models.CharField(blank=True, max_length=100)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notices', to='client.clientprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notices_filed', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_email', models.EmailField(blank=True, max_length=254)),
                ('dispute_type', models.CharField(choices=[('INCORRECT_DATA', 'Incorrect Data'), ('WRONG_PERSON', 'Wrong Person / Identity Error'), ('SETTLED_DEBT', 'Debt Already Settled'), ('FRAUD', 'Fraudulent Record'), ('OTHER', 'Other')], max_length=20)),
                ('field_disputed', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='client.clientprofile')),
                ('filed_by_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_filed', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_key_name', models.CharField(blank=True, max_length=100)),
                ('query_type', models.CharField(choices=[('CREDIT_CHECK', 'Credit Report View'), ('SCORE_CHECK', 'Credit Score Check'), ('PROFILE_LOOKUP', 'Profile Lookup'), ('TPAPI_CHECK', 'Third-Party API Check')], max_length=20)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_logs', to='client.clientprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_made', to='users.userprofile')),
            ],
            options={
                'ordering': ['-queried_at'],
                'indexes': [models.Index(fields=['client', '-queried_at'], name='client_enqu_client__0f1ae0_idx')],
            },
        ),
    ]
