# Generated by Django 6.0.4 on 2026-07-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_clientprofile_dcc_status_clientconsent_and_more'),
        ('users', '0003_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconsent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_obtained', to='users.userprofile'),
        ),
    ]
