# Generated by Django 6.0.4 on 2026-07-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_consent_tenant_nullable'),
        ('users', '0004_rename_plan_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_types', models.JSONField(default=list, help_text='List of alert type codes to watch. Empty = ALL changes.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='client.clientprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='users.userprofile')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('tenant', 'client')},
            },
        ),
    ]
