# Generated by Django 6.0.4 on 2026-07-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_client_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='5 business days after submission — auto-escalate if still open.', null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated — SLA Breached'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=15),
        ),
        migrations.CreateModel(
            name='ClientWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_types', models.JSONField(default=list, help_text='Which alert types fired.')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('sent_immediately', models.BooleanField(default=False, help_text='True if an immediate email was sent; False if queued for digest.')),
                ('digest_sent_at', models.DateTimeField(blank=True, help_text='Set when this event was included in a digest email.', null=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client.clientwatch')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
    ]
