# Generated by Django 6.0.4 on 2026-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0007_branch_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_account', to='client.clientprofile')),
            ],
            options={
                'verbose_name': 'Borrower portal account',
            },
        ),
    ]
