# Generated by Django 6.0.4 on 2026-07-17 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREDIT_CHECK', 'Credit check'), ('PROFILE_LOOKUP', 'Profile lookup'), ('LOANS_LOOKUP', 'Loans lookup'), ('TRANSACTIONS_LOOKUP', 'Transactions lookup'), ('FEED_SYNC', 'Feed records synced')], max_length=30)),
                ('units', models.PositiveIntegerField(default=1, help_text='1 per lookup/check; record count for feed syncs.')),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='PGK', max_length=10)),
                ('monthly_base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat monthly access fee per tenant.', max_digits=10)),
                ('price_per_credit_check', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged for each consolidated credit check.', max_digits=8)),
                ('price_per_profile_lookup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged for each single profile/loans/transactions lookup.', max_digits=8)),
                ('price_per_record_synced', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Charged per record ingested from the tenant feed.', max_digits=8)),
            ],
            options={
                'verbose_name': 'Pricing settings',
                'verbose_name_plural': 'Pricing settings',
            },
        ),
    ]
