# Generated by Django 6.0.4 on 2026-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['tenant', 'created_at'], name='api_apiusag_tenant__b88985_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['action', 'created_at'], name='api_apiusag_action_dda2ce_idx'),
        ),
    ]
