# Generated by Django 6.0.4 on 2026-07-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('users', '0002_userprofile_credit_check_window_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCheckAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_cuid', models.CharField(help_text='CUID of the client whose credit data was unlocked.', max_length=100)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_check_accesses', to='users.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'client_cuid', 'expires_at'], name='api_creditc_tenant__9d90ab_idx')],
            },
        ),
    ]
