# Generated by Django 6.0.4 on 2026-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_billing_snapshot_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_portal_enabled', models.BooleanField(default=False, help_text='Allow borrowers to log in to the self-service portal to view their credit file and submit disputes.')),
                ('default_expiry_years', models.PositiveIntegerField(default=7, help_text='Defaults older than this many years are automatically archived.')),
                ('require_consent_before_share', models.BooleanField(default=False, help_text='Block cross-tenant data sharing unless a valid ClientConsent exists.')),
                ('alert_on_status_change', models.BooleanField(default=True, help_text="Email the originating lender when their borrower's DCC status changes.")),
                ('alert_on_new_view', models.BooleanField(default=False, help_text="Email the originating lender when another tenant pays to view their borrower's credit report.")),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
