# Generated by Django 6.0.4 on 2026-07-23 21:16

from decimal import Decimal
from django.db import migrations, models


def seed_plan_pricing(apps, schema_editor):
    from decimal import Decimal
    PricingSettings = apps.get_model('api', 'PricingSettings')
    plans = [
        dict(plan='FREE',     joining_fee=Decimal('0'),    monthly_base_fee=Decimal('0'),
             billing_period='MONTHLY',     price_per_credit_check=Decimal('10.00'),
             free_credit_checks=0,  price_per_profile_lookup=Decimal('0'),
             price_per_record_synced=Decimal('0'), price_per_rating_check=Decimal('0')),
        dict(plan='SME',      joining_fee=Decimal('1000'), monthly_base_fee=Decimal('180'),
             billing_period='MONTHLY',     price_per_credit_check=Decimal('2.50'),
             free_credit_checks=0,  price_per_profile_lookup=Decimal('0'),
             price_per_record_synced=Decimal('0'), price_per_rating_check=Decimal('0')),
        dict(plan='BUSINESS', joining_fee=Decimal('1000'), monthly_base_fee=Decimal('180'),
             billing_period='FORTNIGHTLY', price_per_credit_check=Decimal('1.50'),
             free_credit_checks=100, price_per_profile_lookup=Decimal('0'),
             price_per_record_synced=Decimal('0'), price_per_rating_check=Decimal('0')),
    ]
    for p in plans:
        PricingSettings.objects.update_or_create(plan=p['plan'], defaults={k:v for k,v in p.items() if k != 'plan'})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='billing_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('FORTNIGHTLY', 'Fortnightly')], default='MONTHLY', help_text='How often the base fee is charged.', max_length=15),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='free_credit_checks',
            field=models.PositiveIntegerField(default=0, help_text='Number of credit checks included free each billing period (Business plan: 100).'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='joining_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time joining/setup fee charged when a tenant signs up on this plan.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free Plan'), ('SME', 'SME Plan'), ('BUSINESS', 'Business Plan')], default='FREE', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='monthly_base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat recurring access fee per billing period.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='price_per_credit_check',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per credit report view after any free-check allowance is used.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='price_per_profile_lookup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per profile/loans/transactions lookup.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='price_per_rating_check',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rating-only lookup (used by tenant auto credit-check).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='price_per_record_synced',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Per record ingested from the tenant feed.', max_digits=8),
        ),
    migrations.RunPython(seed_plan_pricing, migrations.RunPython.noop),
    ]