# Generated by Django 6.0.4 on 2026-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('loan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='loanfile',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='loan.loan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loanref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='paymentuploads',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='paymentuploads',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='upload_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loan.paymentuploads'),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.clientprofile'),
        ),
        migrations.AddField(
            model_name='statement',
            name='loanref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='statement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
    ]
