# Generated by Django 6.0.4 on 2026-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_clientprofile_dcc_status_clientconsent_and_more'),
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_type', models.CharField(choices=[('PERSONAL', 'Personal Guarantee'), ('JOINT', 'Joint Borrower'), ('PARTIAL', 'Partial Guarantee')], default='PERSONAL', max_length=10)),
                ('guarantee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_loans', to='client.clientprofile')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loan.loan')),
            ],
            options={
                'unique_together': {('loan', 'guarantor')},
            },
        ),
    ]
