# Generated by Django 6.0.4 on 2026-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('luid', models.CharField(blank=True, max_length=50, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('PAYMENT', 'PAYMENT'), ('DEFAULT', 'DEFAULT'), ('OTHER', 'OTHER')], max_length=255, null=True)),
                ('s_count', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField()),
                ('statement', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('arrears', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('interest_on_default', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('default_interest_collected', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
    ]
