# Generated by Django 6.0.4 on 2026-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('key_hash', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(max_length=10, unique=True)),
                ('permissions', models.JSONField(default=list, help_text='List of allowed scope strings')),
                ('rate_limit_per_day', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Third-party API key',
            },
        ),
        migrations.CreateModel(
            name='TpApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('cuid', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveIntegerField(default=200)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='thirdparty_api.thirdpartyapikey')),
            ],
            options={
                'ordering': ['-queried_at'],
                'indexes': [models.Index(fields=['api_key', '-queried_at'], name='thirdparty__api_key_0b95fd_idx')],
            },
        ),
    ]
