# Generated by Django 6.0.4 on 2026-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin1', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultlistsubmission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_default', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='delistrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='delistrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='delistrequestfeedback',
            name='delist_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.delistrequest'),
        ),
        migrations.AddField(
            model_name='delistrequestfeedback',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
