# Generated by Django 6.0.4 on 2026-07-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_initial'),
        ('client', '0009_consent_tenant_nullable'),
        ('users', '0003_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open — Assessing'), ('NEGOTIATING', 'Actively Negotiating'), ('OFFER_MADE', 'Settlement Offer Made'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Offer Rejected'), ('SETTLED', 'Settled — Paid / Agreed'), ('CLOSED', 'Closed — No Resolution')], default='OPEN', max_length=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_settlement_date', models.DateField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_doc', models.FileField(blank=True, null=True, upload_to='settlements/')),
                ('notes', models.TextField(blank=True)),
                ('borrower_email', models.EmailField(blank=True, max_length=254)),
                ('borrower_phone', models.CharField(blank=True, max_length=30)),
                ('assigned_dcc_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokered_settlements', to='users.userprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='client.clientprofile')),
                ('default_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='client.defaultnotice')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_initiated', to='users.userprofile')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload_batches/')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PENDING_REVIEW', 'Pending Review'), ('PARTIALLY_VERIFIED', 'Partially Verified'), ('COMPLETED', 'Completed')], default='PENDING_REVIEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('DCC', 'DCC Officer'), ('LENDER', 'Lender'), ('BORROWER', 'Borrower'), ('SYSTEM', 'System')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='settlement_msgs/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal DCC notes — not visible to lender/borrower')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admin1.debtsettlement')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('CONTACTED', 'Borrower Contacted'), ('WAITING', 'Awaiting Response'), ('VERIFIED', 'Verified — Admitted'), ('REJECTED', 'Rejected — Not Admitted'), ('HOLD', 'On Hold')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_method', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone Call'), ('SMS', 'SMS'), ('IN_PERSON', 'In Person'), ('LETTER', 'Physical Letter')], max_length=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('lender_feedback', models.TextField(blank=True)),
                ('lender_notified', models.BooleanField(default=False)),
                ('lender_notified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to='users.userprofile')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='admin1.recorduploadbatch')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_case', to='client.clientprofile')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_cases', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone Call'), ('SMS', 'SMS'), ('IN_PERSON', 'In Person'), ('LETTER', 'Physical Letter')], max_length=12)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(blank=True, help_text='e.g. answered, no reply, confirmed, denied', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='admin1.verificationcase')),
                ('contacted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_attempts', to='users.userprofile')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
    ]
